# Generated by Django 5.0.6 on 2024-05-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='cities',
        ),
        migrations.AlterModelTable(
            name='pointofinterest',
            table='points_of_interest',
        ),
    ]
